// Animations for: AnimatedSprite2D
// Generated by Godot2SGDK

// Animation: idle
// Frames: 2, Speed: 5.0, Loop: TRUE
const u16 animated_sprite_2d_idle_frames[] = {
    0, 1
};

const u16 animated_sprite_2d_idle_durations[] = {
    60, 60
};

const Animation animated_sprite_2d_idle = {
    2,  // frame_count
    animated_sprite_2d_idle_frames,  // frames
    animated_sprite_2d_idle_durations,  // durations
    500,  // speed
    TRUE  // loop
};

// Animation: running
// Frames: 4, Speed: 5.0, Loop: FALSE
const u16 animated_sprite_2d_running_frames[] = {
    0, 1, 2, 3
};

const u16 animated_sprite_2d_running_durations[] = {
    60, 60, 60, 60
};

const Animation animated_sprite_2d_running = {
    4,  // frame_count
    animated_sprite_2d_running_frames,  // frames
    animated_sprite_2d_running_durations,  // durations
    500,  // speed
    FALSE  // loop
};

