// Collision: CollisionPolygon2D
// Generated by Godot2SGDK

// Polygon with 4 points
const CollisionPolygon collisionpolygon2d = {
    4,  // point_count
    (Vector2[]){{3, -25}, {-21, -3}, {1, 11}, {16, 0}},  // points
    {0, -2},  // position
    0  // is_trigger
};
