// Auto-generated by Godot2SGDK
// {timestamp}

#ifndef {header_guard}
#define {header_guard}

#define {resource_name_upper}_WIDTH {width}
#define {resource_name_upper}_HEIGHT {height}
#define {resource_name_upper}_SIZE {size}

const unsigned short {resource_name_lower}_data[] = {
    {data}
};

#endif // {header_guard}